configdirectory: /var/lib/cyrus
proc_path: /run/cyrus/proc
mboxname_lockpath: /run/cyrus/lock
partition-default: /var/spool/cyrus/mail
defaultpartition: default
admins: cyrus@example.test
sasl_pwcheck_method: auxprop
sasl_auxprop_plugin: sasldb
sasl_mech_list: PLAIN LOGIN
allowplaintext: yes
virtdomains: userid
defaultdomain: example.test
servername: example.test
unixhierarchysep: yes
altnamespace: yes
imapidlepoll: 60
autocreate_quota: 1000000
